server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app1
    username: root
    password: bhanuchander
  jpa:
    generate-ddl: true
    show-sql: true
productApi: http://localhost:8080/api/products
logging:
  level:
    '[org.springframework.web.reactive]': trace